#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#bug des fois des raccourcis disparaisse
# desinstaller et reinstaller xorg-server-utils et xorg-xmodmap
#xmodmap "/home/yoshi/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
#Installation avec feh (dispo dans les dépôts : crée un .fehbg
#/bin/bash /home/yoshi/.fehbg &
conky &
xrdb /home/yoshi/.Xresources &
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/yoshi/.fluxbox/log"

